import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import './globals.css'

import Header from '~/components/header'

import ThemeContextProvider from '~/contexts/theme-context'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'thanhtrairo',
  description: 'Generated by thanhtrairo',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={`${inter.className} max-w-[100dvw] overflow-x-hidden`}>
        <ThemeContextProvider>
          <div className="min-h-[100dvh] bg-white text-black dark:bg-black-c dark:text-white-c">
            <div className="container mx-auto px-2 sm:px-4 md:px-8 lg:px-12 xl:px-16 2xl:px-20">
              <Header />
              {children}
            </div>
          </div>
        </ThemeContextProvider>
      </body>
    </html>
  )
}
